### PR TITLE
s/covid19/covid-19/g

### PR DESCRIPTION
**Pull request by tomkralidis**
Purely cosmetic change to align everything to `covid-19` in this repo.

### CODE REVIEW

**Comment by justb4** [comment]
Quite a change. Can be done, but also changes URL. Hopefully not yet communicated, like with OGC? What do you think @francbartoli ?

**Comment by francbartoli** [comment]
@tomkralidis @justb4 no worries not done yet, I'll do later today after we check the change

**Comment by justb4** [comment]
Forget my remark: the external URL is not affected as it is determined here: https://github.com/geopython/demo.pygeoapi.io/blob/master/services/pygeoapi_covid-19/docker-compose.yml#L25 . I can redeploy, as that part is not yet automatic and some processes/mounts change.

**Comment by francbartoli** [comment]
@justb4 If you can wait I'll send the changes for Italy after the completion of the meeting notes

**Comment by justb4** [comment]
Sorry, just reading your remark now, but it takes only a few seconds. Possibly can automate with GitHub hook.

**Pull request merged**
